# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# theme: jekyll-theme-so-simple
remote_theme: mmistakes/so-simple-theme

locale: en-US
title: "YONDU UDONTA"
description: "I'm Mary Poppins, Y'all!"
baseurl: ""
url: "https://boreum0302.github.io"
logo: "/images/yondu-udonta-logo.png"
date_format: "%B %-d, %Y"
read_time: false
words_per_minute: 
mathjax:
  enable: true
  combo: "tex-svg"
  tags: "ams"
google_fonts:
  - name: "Noto Serif KR"
    weights: "200,600"
  - name: "Noto Sans KR"
    weights: "200,600
  - name: "Nanum Gothic Coding"
    weights: "400,700"
google_analytics: ""
google_site_verification: "UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Collections
collections:
  photos:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Yondu Udonta
  picture: "/images/yondu-udonta-logo.png"
  email: boreum0302@snu.ac.kr
  links:
    - title: GitHub
      url: https://github.com/boreum0302
      icon: fab fa-github-square
    - title: e-mail
      url: mailto:boreum0302@snu.ac.kr
      icon: fas fa-envelope-square

footer_links:
    - title: GitHub
      url: https://github.com/boreum0302
      icon: fab fa-github-square
    - title: e-mail
      url: mailto:boreum0302@snu.ac.kr
      icon: fas fa-envelope-square
      
copyright: Powered by [**Jekyll**](https://jekyllrb.com/) and [**So Simple Theme**](https://github.com/mmistakes/so-simple-theme).
